import type {
  Product,
  Subscription,
  Order,
  DeliveryTask,
  User,
  DashboardStats,
} from './types';

// TODO: Replace with API call → GET /api/products
export const MOCK_PRODUCTS: readonly Product[] = [
  {
    id: 'p1',
    name: 'Full Cream Milk',
    category: 'dairy',
    price: 32,
    unit: '500ml',
    emoji: '🥛',
    description:
      'Rich, creamy full-fat milk sourced directly from local farms. Packed with calcium and essential nutrients.',
    available: true,
    stock: 250,
  },
  {
    id: 'p2',
    name: 'Toned Milk',
    category: 'dairy',
    price: 28,
    unit: '500ml',
    emoji: '🥛',
    description:
      'Lighter toned milk with reduced fat content. Perfect for everyday cooking and drinking.',
    available: true,
    stock: 180,
  },
  {
    id: 'p3',
    name: 'Fresh Curd',
    category: 'dairy',
    price: 40,
    unit: '400g',
    emoji: '🫙',
    description:
      'Thick, creamy curd made from our farm-fresh milk. Naturally probiotic with no added cultures.',
    available: true,
    stock: 90,
  },
  {
    id: 'p4',
    name: 'Soft Paneer',
    category: 'dairy',
    price: 120,
    unit: '200g',
    emoji: '🧀',
    description:
      'Soft, fresh cottage cheese made daily in small batches. Zero preservatives, maximum freshness.',
    available: true,
    stock: 45,
  },
  {
    id: 'p5',
    name: 'A2 Cow Ghee',
    category: 'dairy',
    price: 280,
    unit: '250ml',
    emoji: '🫙',
    description:
      'Hand-churned pure A2 ghee using the traditional bilona process. Deep golden colour, rich aroma.',
    available: true,
    stock: 30,
  },
  {
    id: 'p6',
    name: 'White Butter',
    category: 'dairy',
    price: 80,
    unit: '100g',
    emoji: '🧈',
    description:
      'Fresh unsalted white butter churned every morning. Smooth texture, clean dairy flavour.',
    available: true,
    stock: 60,
  },
  {
    id: 'p7',
    name: 'Sunflower Microgreens',
    category: 'greens',
    price: 65,
    unit: '50g',
    emoji: '🌱',
    description:
      'Nutrient-dense sunflower microgreens harvested at peak nutrition. 40× more nutrients than mature greens.',
    available: true,
    stock: 25,
  },
  {
    id: 'p8',
    name: 'Free Range Eggs',
    category: 'eggs',
    price: 84,
    unit: '6 pcs',
    emoji: '🥚',
    description:
      'Farm-fresh free-range eggs. Hens raised on open pastures, rich in protein and omega-3.',
    available: false,
    stock: 0,
  },
];

// TODO: Replace with API call → GET /api/users
export const MOCK_USERS: readonly User[] = [
  {
    id: 'u1',
    name: 'Priya Sharma',
    email: 'priya.sharma@gmail.com',
    phone: '+91 98765 43210',
    address: '12, Green Park Extension, New Delhi - 110016',
    joinedAt: '2025-03-15',
    activeSubscriptions: 1,
    totalOrders: 47,
    totalSpend: 4820,
  },
  {
    id: 'u2',
    name: 'Rahul Mehta',
    email: 'rahul.mehta@gmail.com',
    phone: '+91 98123 45678',
    address: '45, Koramangala 5th Block, Bangalore - 560095',
    joinedAt: '2025-01-10',
    activeSubscriptions: 2,
    totalOrders: 89,
    totalSpend: 9240,
  },
  {
    id: 'u3',
    name: 'Anita Patel',
    email: 'anita.patel@outlook.com',
    phone: '+91 99887 76655',
    address: '78, Banjara Hills Road No. 3, Hyderabad - 500034',
    joinedAt: '2025-04-22',
    activeSubscriptions: 1,
    totalOrders: 28,
    totalSpend: 2960,
  },
  {
    id: 'u4',
    name: 'Vikram Singh',
    email: 'vikram.singh@yahoo.com',
    phone: '+91 97755 66544',
    address: '23, Andheri West, Mumbai - 400053',
    joinedAt: '2024-11-05',
    activeSubscriptions: 0,
    totalOrders: 112,
    totalSpend: 11500,
  },
  {
    id: 'u5',
    name: 'Deepika Nair',
    email: 'deepika.nair@gmail.com',
    phone: '+91 96644 55433',
    address: '56, T Nagar, Chennai - 600017',
    joinedAt: '2025-02-14',
    activeSubscriptions: 1,
    totalOrders: 64,
    totalSpend: 6720,
  },
  {
    id: 'u6',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@gmail.com',
    phone: '+91 95533 44322',
    address: '34, Adyar, Chennai - 600020',
    joinedAt: '2026-01-08',
    activeSubscriptions: 1,
    totalOrders: 12,
    totalSpend: 1240,
  },
];

// TODO: Replace with API call → GET /api/subscriptions
export const MOCK_SUBSCRIPTIONS: readonly Subscription[] = [
  {
    id: 's1',
    userId: 'u1',
    userName: 'Priya Sharma',
    userPhone: '+91 98765 43210',
    deliveryAddress: '12, Green Park Extension, New Delhi - 110016',
    items: [
      { productId: 'p1', productName: 'Full Cream Milk', quantity: 2, pricePerUnit: 32 },
      { productId: 'p3', productName: 'Fresh Curd', quantity: 1, pricePerUnit: 40 },
    ],
    frequency: 'daily',
    startDate: '2025-03-20',
    status: 'active',
    deliverySlot: '6AM-8AM',
    nextDelivery: '2026-05-21',
    monthlyTotal: 3120,
  },
  {
    id: 's2',
    userId: 'u2',
    userName: 'Rahul Mehta',
    userPhone: '+91 98123 45678',
    deliveryAddress: '45, Koramangala 5th Block, Bangalore - 560095',
    items: [
      { productId: 'p1', productName: 'Full Cream Milk', quantity: 1, pricePerUnit: 32 },
      { productId: 'p4', productName: 'Soft Paneer', quantity: 2, pricePerUnit: 120 },
      { productId: 'p7', productName: 'Sunflower Microgreens', quantity: 1, pricePerUnit: 65 },
    ],
    frequency: 'alternate-days',
    startDate: '2025-01-15',
    status: 'active',
    deliverySlot: '7AM-9AM',
    nextDelivery: '2026-05-21',
    monthlyTotal: 4375,
  },
  {
    id: 's3',
    userId: 'u3',
    userName: 'Anita Patel',
    userPhone: '+91 99887 76655',
    deliveryAddress: '78, Banjara Hills Road No. 3, Hyderabad - 500034',
    items: [
      { productId: 'p2', productName: 'Toned Milk', quantity: 2, pricePerUnit: 28 },
      { productId: 'p6', productName: 'White Butter', quantity: 1, pricePerUnit: 80 },
    ],
    frequency: 'daily',
    startDate: '2025-05-01',
    status: 'paused',
    deliverySlot: '8AM-10AM',
    nextDelivery: '2026-05-25',
    monthlyTotal: 2280,
  },
  {
    id: 's4',
    userId: 'u5',
    userName: 'Deepika Nair',
    userPhone: '+91 96644 55433',
    deliveryAddress: '56, T Nagar, Chennai - 600017',
    items: [
      { productId: 'p5', productName: 'A2 Cow Ghee', quantity: 1, pricePerUnit: 280 },
      { productId: 'p1', productName: 'Full Cream Milk', quantity: 2, pricePerUnit: 32 },
    ],
    frequency: 'weekly',
    startDate: '2025-02-20',
    status: 'active',
    deliverySlot: '6AM-8AM',
    nextDelivery: '2026-05-25',
    monthlyTotal: 1408,
  },
  {
    id: 's5',
    userId: 'u6',
    userName: 'Arjun Kapoor',
    userPhone: '+91 95533 44322',
    deliveryAddress: '34, Adyar, Chennai - 600020',
    items: [
      { productId: 'p3', productName: 'Fresh Curd', quantity: 2, pricePerUnit: 40 },
      { productId: 'p7', productName: 'Sunflower Microgreens', quantity: 2, pricePerUnit: 65 },
    ],
    frequency: 'daily',
    startDate: '2026-01-10',
    status: 'active',
    deliverySlot: '7AM-9AM',
    nextDelivery: '2026-05-21',
    monthlyTotal: 3750,
  },
];

// TODO: Replace with API call → GET /api/orders
export const MOCK_ORDERS: readonly Order[] = [
  {
    id: 'ORD-001',
    userId: 'u1',
    userName: 'Priya Sharma',
    type: 'subscription',
    items: [
      { productId: 'p1', productName: 'Full Cream Milk', quantity: 2, price: 32 },
      { productId: 'p3', productName: 'Fresh Curd', quantity: 1, price: 40 },
    ],
    total: 104,
    status: 'delivered',
    deliveryDate: '2026-05-20',
    deliveryAddress: '12, Green Park Extension, New Delhi',
    createdAt: '2026-05-19T22:00:00Z',
  },
  {
    id: 'ORD-002',
    userId: 'u2',
    userName: 'Rahul Mehta',
    type: 'subscription',
    items: [
      { productId: 'p1', productName: 'Full Cream Milk', quantity: 1, price: 32 },
      { productId: 'p4', productName: 'Soft Paneer', quantity: 2, price: 120 },
    ],
    total: 272,
    status: 'out-for-delivery',
    deliveryDate: '2026-05-20',
    deliveryAddress: '45, Koramangala 5th Block, Bangalore',
    createdAt: '2026-05-19T22:00:00Z',
  },
  {
    id: 'ORD-003',
    userId: 'u4',
    userName: 'Vikram Singh',
    type: 'one-time',
    items: [{ productId: 'p5', productName: 'A2 Cow Ghee', quantity: 2, price: 280 }],
    total: 560,
    status: 'confirmed',
    deliveryDate: '2026-05-21',
    deliveryAddress: '23, Andheri West, Mumbai',
    createdAt: '2026-05-20T09:30:00Z',
  },
  {
    id: 'ORD-004',
    userId: 'u5',
    userName: 'Deepika Nair',
    type: 'subscription',
    items: [{ productId: 'p1', productName: 'Full Cream Milk', quantity: 2, price: 32 }],
    total: 64,
    status: 'delivered',
    deliveryDate: '2026-05-20',
    deliveryAddress: '56, T Nagar, Chennai',
    createdAt: '2026-05-19T22:00:00Z',
  },
  {
    id: 'ORD-005',
    userId: 'u6',
    userName: 'Arjun Kapoor',
    type: 'subscription',
    items: [
      { productId: 'p3', productName: 'Fresh Curd', quantity: 2, price: 40 },
      { productId: 'p7', productName: 'Sunflower Microgreens', quantity: 2, price: 65 },
    ],
    total: 210,
    status: 'out-for-delivery',
    deliveryDate: '2026-05-20',
    deliveryAddress: '34, Adyar, Chennai',
    createdAt: '2026-05-19T22:00:00Z',
  },
  {
    id: 'ORD-006',
    userId: 'u1',
    userName: 'Priya Sharma',
    type: 'one-time',
    items: [
      { productId: 'p4', productName: 'Soft Paneer', quantity: 1, price: 120 },
      { productId: 'p6', productName: 'White Butter', quantity: 2, price: 80 },
    ],
    total: 280,
    status: 'pending',
    deliveryDate: '2026-05-21',
    deliveryAddress: '12, Green Park Extension, New Delhi',
    createdAt: '2026-05-20T11:00:00Z',
  },
  {
    id: 'ORD-007',
    userId: 'u3',
    userName: 'Anita Patel',
    type: 'one-time',
    items: [{ productId: 'p2', productName: 'Toned Milk', quantity: 3, price: 28 }],
    total: 84,
    status: 'cancelled',
    deliveryDate: '2026-05-20',
    deliveryAddress: '78, Banjara Hills, Hyderabad',
    createdAt: '2026-05-19T15:00:00Z',
  },
];

// TODO: Replace with API call → GET /api/deliveries/today
export const MOCK_TODAY_DELIVERIES: DeliveryTask[] = [
  {
    id: 'd1',
    orderId: 'ORD-001',
    customerName: 'Priya Sharma',
    address: '12, Green Park Extension, New Delhi - 110016',
    phone: '+91 98765 43210',
    itemsSummary: '2× Full Cream Milk, 1× Fresh Curd',
    slot: '6AM-8AM',
    status: 'delivered',
    notes: '',
    sequence: 1,
  },
  {
    id: 'd2',
    orderId: 'ORD-004',
    customerName: 'Deepika Nair',
    address: '56, T Nagar, Chennai - 600017',
    phone: '+91 96644 55433',
    itemsSummary: '2× Full Cream Milk',
    slot: '6AM-8AM',
    status: 'delivered',
    notes: 'Leave at door if no answer',
    sequence: 2,
  },
  {
    id: 'd3',
    orderId: 'ORD-005',
    customerName: 'Arjun Kapoor',
    address: '34, Adyar, Chennai - 600020',
    phone: '+91 95533 44322',
    itemsSummary: '2× Fresh Curd, 2× Sunflower Microgreens',
    slot: '7AM-9AM',
    status: 'pending',
    notes: '',
    sequence: 3,
  },
  {
    id: 'd4',
    orderId: 'ORD-002',
    customerName: 'Rahul Mehta',
    address: '45, Koramangala 5th Block, Bangalore - 560095',
    phone: '+91 98123 45678',
    itemsSummary: '1× Full Cream Milk, 2× Soft Paneer',
    slot: '7AM-9AM',
    status: 'pending',
    notes: 'Call before arriving',
    sequence: 4,
  },
  {
    id: 'd5',
    orderId: 'sub-auto-5',
    customerName: 'Meena Krishnaswamy',
    address: '89, Adyar Layout, Chennai - 600028',
    phone: '+91 94422 33211',
    itemsSummary: '1× Toned Milk, 1× Fresh Curd',
    slot: '7AM-9AM',
    status: 'pending',
    notes: '',
    sequence: 5,
  },
  {
    id: 'd6',
    orderId: 'sub-auto-6',
    customerName: 'Suresh Babu',
    address: '12, Mylapore, Chennai - 600004',
    phone: '+91 93311 22100',
    itemsSummary: '2× Toned Milk, 1× White Butter',
    slot: '8AM-10AM',
    status: 'pending',
    notes: '',
    sequence: 6,
  },
  {
    id: 'd7',
    orderId: 'sub-auto-7',
    customerName: 'Kavitha Rajan',
    address: '67, Anna Nagar East, Chennai - 600102',
    phone: '+91 92200 11099',
    itemsSummary: '1× Full Cream Milk, 1× Soft Paneer',
    slot: '8AM-10AM',
    status: 'pending',
    notes: 'Flat 302, use elevator',
    sequence: 7,
  },
  {
    id: 'd8',
    orderId: 'sub-auto-8',
    customerName: 'Rajesh Kumar',
    address: '101, Besant Nagar, Chennai - 600090',
    phone: '+91 91188 99088',
    itemsSummary: '3× Full Cream Milk, 1× A2 Cow Ghee',
    slot: '8AM-10AM',
    status: 'failed',
    notes: 'Customer not available. Will redeliver tomorrow.',
    sequence: 8,
  },
];

// TODO: Replace with API call → GET /api/dashboard/stats
export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalActiveUsers: 12480,
  totalActiveSubscriptions: 9340,
  todayDeliveries: 8,
  todayCompletedDeliveries: 2,
  todayRevenue: 18640,
  pendingOrders: 3,
  lowStockProducts: 2,
};

// TODO: Replace with API call → GET /api/revenue/weekly
export const MOCK_WEEKLY_REVENUE: readonly { day: string; revenue: number }[] = [
  { day: 'Mon', revenue: 14200 },
  { day: 'Tue', revenue: 16800 },
  { day: 'Wed', revenue: 15400 },
  { day: 'Thu', revenue: 18900 },
  { day: 'Fri', revenue: 21300 },
  { day: 'Sat', revenue: 24100 },
  { day: 'Sun', revenue: 18640 },
];
